"""updated password in users table

Revision ID: 03393d0babbd
Revises: 29a4fdf0b2fd
Create Date: 2023-08-30 14:49:54.593954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03393d0babbd'
down_revision = '29a4fdf0b2fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.String(), nullable=False))
        batch_op.alter_column('small_kids',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('own_pets',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('own_pets',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('small_kids',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('_password')

    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=15), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=False),
    sa.Column('small_kids', sa.BOOLEAN(), nullable=True),
    sa.Column('own_pets', sa.BOOLEAN(), nullable=True),
    sa.Column('space', sa.VARCHAR(), nullable=True),
    sa.Column('_password', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
